#############################################################################
# Makefile for building: QwtControl
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Oct 10 12:24:48 2012
# Project:  QwtControl.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtControl.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O3 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O3 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qwt5 -I../../muparserx-read-only/parser -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -L/usr/lib/ -L. -lqwt -lmuparser -lmuparserx -lm -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		vardialog.cpp \
		stepresponsedialog.cpp \
		bodedialog.cpp \
		expressiondialog.cpp \
		expressionmodel.cpp \
		varmodel.cpp \
		curvethread.cpp \
		rangeselectordialog.cpp \
		parametersliderdialog.cpp \
		qparameterslider.cpp \
		numericallaplace.cpp \
		curvesegmentthread.cpp \
		curvemodel.cpp moc_mainwindow.cpp \
		moc_vardialog.cpp \
		moc_stepresponsedialog.cpp \
		moc_bodedialog.cpp \
		moc_expressiondialog.cpp \
		moc_expressionmodel.cpp \
		moc_varmodel.cpp \
		moc_curvethread.cpp \
		moc_rangeselectordialog.cpp \
		moc_parametersliderdialog.cpp \
		moc_qparameterslider.cpp \
		moc_curvesegmentthread.cpp \
		moc_curvemodel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		vardialog.o \
		stepresponsedialog.o \
		bodedialog.o \
		expressiondialog.o \
		expressionmodel.o \
		varmodel.o \
		curvethread.o \
		rangeselectordialog.o \
		parametersliderdialog.o \
		qparameterslider.o \
		numericallaplace.o \
		curvesegmentthread.o \
		curvemodel.o \
		moc_mainwindow.o \
		moc_vardialog.o \
		moc_stepresponsedialog.o \
		moc_bodedialog.o \
		moc_expressiondialog.o \
		moc_expressionmodel.o \
		moc_varmodel.o \
		moc_curvethread.o \
		moc_rangeselectordialog.o \
		moc_parametersliderdialog.o \
		moc_qparameterslider.o \
		moc_curvesegmentthread.o \
		moc_curvemodel.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QwtControl.pro
QMAKE_TARGET  = QwtControl
DESTDIR       = 
TARGET        = QwtControl

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_vardialog.h ui_bodedialog.h ui_expressiondialog.h ui_stepresponsedialog.h ui_rangeselectordialog.h ui_parametersliderdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: QwtControl.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtControl.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QwtControl.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QwtControl1.0.0 || $(MKDIR) .tmp/QwtControl1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QwtControl1.0.0/ && $(COPY_FILE) --parents mainwindow.h vardialog.h stepresponsedialog.h bodedialog.h expressiondialog.h expressionmodel.h varmodel.h curvethread.h rangeselectordialog.h parametersliderdialog.h qparameterslider.h numericallaplace.h curvesegmentthread.h curvemodel.h definitions.h .tmp/QwtControl1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp vardialog.cpp stepresponsedialog.cpp bodedialog.cpp expressiondialog.cpp expressionmodel.cpp varmodel.cpp curvethread.cpp rangeselectordialog.cpp parametersliderdialog.cpp qparameterslider.cpp numericallaplace.cpp curvesegmentthread.cpp curvemodel.cpp .tmp/QwtControl1.0.0/ && $(COPY_FILE) --parents mainwindow.ui vardialog.ui bodedialog.ui expressiondialog.ui stepresponsedialog.ui rangeselectordialog.ui parametersliderdialog.ui .tmp/QwtControl1.0.0/ && (cd `dirname .tmp/QwtControl1.0.0` && $(TAR) QwtControl1.0.0.tar QwtControl1.0.0 && $(COMPRESS) QwtControl1.0.0.tar) && $(MOVE) `dirname .tmp/QwtControl1.0.0`/QwtControl1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QwtControl1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_vardialog.cpp moc_stepresponsedialog.cpp moc_bodedialog.cpp moc_expressiondialog.cpp moc_expressionmodel.cpp moc_varmodel.cpp moc_curvethread.cpp moc_rangeselectordialog.cpp moc_parametersliderdialog.cpp moc_qparameterslider.cpp moc_curvesegmentthread.cpp moc_curvemodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_vardialog.cpp moc_stepresponsedialog.cpp moc_bodedialog.cpp moc_expressiondialog.cpp moc_expressionmodel.cpp moc_varmodel.cpp moc_curvethread.cpp moc_rangeselectordialog.cpp moc_parametersliderdialog.cpp moc_qparameterslider.cpp moc_curvesegmentthread.cpp moc_curvemodel.cpp
moc_mainwindow.cpp: expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		mainwindow.h \
		curvesegmentthread.h \
		numericallaplace.h \
		curvemodel.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_vardialog.cpp: vardialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) vardialog.h -o moc_vardialog.cpp

moc_stepresponsedialog.cpp: stepresponsedialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) stepresponsedialog.h -o moc_stepresponsedialog.cpp

moc_bodedialog.cpp: bodedialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) bodedialog.h -o moc_bodedialog.cpp

moc_expressiondialog.cpp: expressiondialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) expressiondialog.h -o moc_expressiondialog.cpp

moc_expressionmodel.cpp: expressionmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) expressionmodel.h -o moc_expressionmodel.cpp

moc_varmodel.cpp: varmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) varmodel.h -o moc_varmodel.cpp

moc_curvethread.cpp: mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h \
		curvethread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) curvethread.h -o moc_curvethread.cpp

moc_rangeselectordialog.cpp: rangeselectordialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) rangeselectordialog.h -o moc_rangeselectordialog.cpp

moc_parametersliderdialog.cpp: qparameterslider.h \
		parametersliderdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) parametersliderdialog.h -o moc_parametersliderdialog.cpp

moc_qparameterslider.cpp: qparameterslider.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qparameterslider.h -o moc_qparameterslider.cpp

moc_curvesegmentthread.cpp: mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h \
		curvesegmentthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) curvesegmentthread.h -o moc_curvesegmentthread.cpp

moc_curvemodel.cpp: mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h \
		curvemodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) curvemodel.h -o moc_curvemodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_vardialog.h ui_bodedialog.h ui_expressiondialog.h ui_stepresponsedialog.h ui_rangeselectordialog.h ui_parametersliderdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_vardialog.h ui_bodedialog.h ui_expressiondialog.h ui_stepresponsedialog.h ui_rangeselectordialog.h ui_parametersliderdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_vardialog.h: vardialog.ui
	/usr/bin/uic vardialog.ui -o ui_vardialog.h

ui_bodedialog.h: bodedialog.ui
	/usr/bin/uic bodedialog.ui -o ui_bodedialog.h

ui_expressiondialog.h: expressiondialog.ui
	/usr/bin/uic expressiondialog.ui -o ui_expressiondialog.h

ui_stepresponsedialog.h: stepresponsedialog.ui
	/usr/bin/uic stepresponsedialog.ui -o ui_stepresponsedialog.h

ui_rangeselectordialog.h: rangeselectordialog.ui
	/usr/bin/uic rangeselectordialog.ui -o ui_rangeselectordialog.h

ui_parametersliderdialog.h: parametersliderdialog.ui
	/usr/bin/uic parametersliderdialog.ui -o ui_parametersliderdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

vardialog.o: vardialog.cpp vardialog.h \
		ui_vardialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vardialog.o vardialog.cpp

stepresponsedialog.o: stepresponsedialog.cpp stepresponsedialog.h \
		ui_stepresponsedialog.h \
		mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stepresponsedialog.o stepresponsedialog.cpp

bodedialog.o: bodedialog.cpp bodedialog.h \
		ui_bodedialog.h \
		mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h \
		curvemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bodedialog.o bodedialog.cpp

expressiondialog.o: expressiondialog.cpp expressiondialog.h \
		ui_expressiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressiondialog.o expressiondialog.cpp

expressionmodel.o: expressionmodel.cpp expressionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressionmodel.o expressionmodel.cpp

varmodel.o: varmodel.cpp varmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o varmodel.o varmodel.cpp

curvethread.o: curvethread.cpp curvethread.h \
		mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvesegmentthread.h \
		numericallaplace.h \
		curvemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curvethread.o curvethread.cpp

rangeselectordialog.o: rangeselectordialog.cpp rangeselectordialog.h \
		ui_rangeselectordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rangeselectordialog.o rangeselectordialog.cpp

parametersliderdialog.o: parametersliderdialog.cpp parametersliderdialog.h \
		qparameterslider.h \
		ui_parametersliderdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parametersliderdialog.o parametersliderdialog.cpp

qparameterslider.o: qparameterslider.cpp qparameterslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qparameterslider.o qparameterslider.cpp

numericallaplace.o: numericallaplace.cpp numericallaplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numericallaplace.o numericallaplace.cpp

curvesegmentthread.o: curvesegmentthread.cpp curvesegmentthread.h \
		mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curvesegmentthread.o curvesegmentthread.cpp

curvemodel.o: curvemodel.cpp curvemodel.h \
		mainwindow.h \
		expressiondialog.h \
		vardialog.h \
		expressionmodel.h \
		varmodel.h \
		rangeselectordialog.h \
		parametersliderdialog.h \
		qparameterslider.h \
		bodedialog.h \
		stepresponsedialog.h \
		curvethread.h \
		numericallaplace.h \
		curvesegmentthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curvemodel.o curvemodel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_vardialog.o: moc_vardialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vardialog.o moc_vardialog.cpp

moc_stepresponsedialog.o: moc_stepresponsedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stepresponsedialog.o moc_stepresponsedialog.cpp

moc_bodedialog.o: moc_bodedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bodedialog.o moc_bodedialog.cpp

moc_expressiondialog.o: moc_expressiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_expressiondialog.o moc_expressiondialog.cpp

moc_expressionmodel.o: moc_expressionmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_expressionmodel.o moc_expressionmodel.cpp

moc_varmodel.o: moc_varmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_varmodel.o moc_varmodel.cpp

moc_curvethread.o: moc_curvethread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_curvethread.o moc_curvethread.cpp

moc_rangeselectordialog.o: moc_rangeselectordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rangeselectordialog.o moc_rangeselectordialog.cpp

moc_parametersliderdialog.o: moc_parametersliderdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parametersliderdialog.o moc_parametersliderdialog.cpp

moc_qparameterslider.o: moc_qparameterslider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qparameterslider.o moc_qparameterslider.cpp

moc_curvesegmentthread.o: moc_curvesegmentthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_curvesegmentthread.o moc_curvesegmentthread.cpp

moc_curvemodel.o: moc_curvemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_curvemodel.o moc_curvemodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

